# Generated by Django 4.2 on 2024-11-14 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watches',
            name='release_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
