# Generated by Django 4.2 on 2024-12-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0003_watches_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Category Name')),
            ],
        ),
        migrations.AddField(
            model_name='watches',
            name='categories',
            field=models.ManyToManyField(to='watches.category'),
        ),
    ]
