# Generated by Django 4.2 on 2024-12-09 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0005_alter_category_options_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='watches',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
