# Generated by Django 4.2 on 2024-12-10 19:16

import core.utils.image_size_validator
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watches', '0007_alter_watches_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watches',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media', validators=[core.utils.image_size_validator.validate_image]),
        ),
    ]
